# Generated by Django 6.0.2 on 2026-02-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ELDLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_miles", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_address", models.CharField(max_length=255)),
                ("pickup_address", models.CharField(max_length=255)),
                ("drop_off_address", models.CharField(max_length=255)),
                (
                    "initial_cycle_hours",
                    models.FloatField(
                        default=0.0, help_text="Hours used in the 70hr/8day cycle"
                    ),
                ),
                (
                    "driver_id",
                    models.TextField(blank=True, default="DVI-0001", max_length=255),
                ),
                (
                    "vehicle_id",
                    models.TextField(blank=True, default="VHI-0001", max_length=255),
                ),
                (
                    "trailer_id",
                    models.TextField(blank=True, default="TLI-0001", max_length=255),
                ),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("route_geometry", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY", "On Duty (not driving)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location_text", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "eld_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="trip.eldlog",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="eldlog",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="trip.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eldlog",
            unique_together={("trip", "date")},
        ),
    ]
